[package]
name = "nfdump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
bzip2 = "0.4.4"
lz4_flex = "0.11.1"
minilzo = "0.2.0"
zstd = "0.13.0"